jobportal/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    # EMPLOYEE
    # accounts/employee/register/
    url(r'^employee/register/$', views.registerEmployee, name='employee-add'),
    url(r'^employee/login/$', views.loginEmployee, name='employee-login'),
    url(r'^employee/logout/$', views.logoutEmployee, name='employee-logout'),
    url(r'^employee/skillmatch/$', views.matchSkill, name='employee-match'),
    url(r'^employee/index/$', login_required(views.indexEmployee.as_view()), name='employee-index'),
    # CLIENT
    url(r'^client/register/$', views.registerClient, name='client-add'),
    url(r'^client/login/$', views.loginClient, name='client-login'),
    url(r'^client/logout/$', views.logoutClient, name='client-logout'),
    url(r'^client/job/$', login_required(views.jobopportunity.as_view()), name='client-job'),
    url(r'^client/index/$', login_required(views.indexClient.as_view()), name='client-index'),
    # APPLICANT
    url(r'^applicant/register/$', views.registerApplicant, name='applicant-add'),
    url(r'^applicant/login/$', views.loginApplicant, name='applicant-login'),
    url(r'^applicant/logout/$', views.logoutApplicant, name='applicant-logout'),
    url(r'^applicant/index/$', login_required(views.indexApplicant.as_view()), name='applicant-index'),
    url(r'^applicant/requirement/$', login_required(views.requirementsApplicant.as_view()),
        name='applicant-requirement'),
    url(r'^applicant/education/$', login_required(views.educationApplicant.as_view()),
        name='applicant-education'),
    url(r'^applicant/skills/$', login_required(views.skillApplicant.as_view()), name='applicant-skill'),
]

webdevtproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from jobportal import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^jobportal/', include('jobportal.urls')),
]

jobportal/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.conf import settings
from django.core.urlresolvers import reverse

# Base User Manager for Custom User.


class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        # Creates and Saves a User with the given email and password

        now = timezone.now()

        if not email:
            raise ValueError('The given email must be set')

        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff,
                          is_active=True,
                          is_superuser=is_superuser,
                          last_login=now,
                          date_joined=now,
                          **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)

# Base Custom User


class CustomUser(AbstractBaseUser, PermissionsMixin):
    UserID = models.AutoField(primary_key=True)
    email = models.EmailField(blank=True, unique=True)
    First_Name = models.CharField(max_length=20)
    Last_Name = models.CharField(max_length=20)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['First_Name', 'Last_Name']

    objects = CustomUserManager()

    class Meta:  # Meta Data: Anything that isn't a field
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def __str__(self):
        full_info = "%s %s - %s" % (self.First_Name, self.Last_Name, self.email)
        return full_info.strip()

    def get_absolute_url(self):
        return "users/%s/" % urlquote(self.email)

    def get_full_name(self):
        # Returns the first_name with the last_name
        full_name = "%s %s" % (self.First_Name, self.Last_Name)
        return self.full_name.strip()

    def get_short_name(self):
        # Returns the short name for the user
        return self.First_Name

    def email_user(self, subject, message, from_email=None):
        # sends an email to this user
        send_mail(subject, message, from_email, [self.email])


# Classes with ForeignKey
class Applicant(CustomUser):
    ApplicantID = models.AutoField(primary_key=True)
    NickName = models.CharField(max_length=50)
    Birth_Date = models.DateField()
    Birth_Place = models.CharField(max_length=100)
    Gender = models.CharField(max_length=10)
    Civil_Status = models.CharField(max_length=20)
    Picture = models.FileField()
    Status = models.CharField(max_length=50, default="Applying")
    Bldg_No = models.CharField(max_length=50)
    Street = models.CharField(max_length=50)
    Municipality = models.CharField(max_length=50)
    City = models.CharField(max_length=50)
    Country = models.CharField(max_length=50)
    Phone = models.CharField(max_length=15)
    Mobile = models.CharField(max_length=11)

    def __str__(self):
        applicant = "%s - %s" % (self.NickName, self.Status)
        return applicant.strip()


class Employee(CustomUser):
    EmployeeID = models.AutoField(primary_key=True)
    # User = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    Employee_No = models.CharField(max_length=15)
    Civil_Status = models.CharField(max_length=20)
    Phone = models.CharField(max_length=15)
    Mobile = models.CharField(max_length=11)
    Bldg_No = models.CharField(max_length=50)
    Street = models.CharField(max_length=50)
    Municipality = models.CharField(max_length=50)
    City = models.CharField(max_length=50)
    Country = models.CharField(max_length=50)

    def __str__(self):
        data = "%s - %s %s" % (self.Employee_No, self.First_Name, self.Last_Name)
        return self.data.strip()


class Client(CustomUser):
    ClientID = models.AutoField(primary_key=True)
    # User = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    Company_Name = models.CharField(max_length=20)
    Logo = models.FileField()
    Bldg_No = models.CharField(max_length=50)
    Street = models.CharField(max_length=50)
    Municipality = models.CharField(max_length=50)
    City = models.CharField(max_length=50)
    Country = models.CharField(max_length=50)
    Phone = models.CharField(max_length=15)
    Mobile = models.CharField(max_length=11)
    Website = models.URLField()

    def __str__(self):
        return self.Company_Name


class Requirement(models.Model):
    RequirementID = models.AutoField(primary_key=True)
    User = models.OneToOneField(Applicant, on_delete=models.CASCADE)
    SSS = models.FileField()
    Phil_Health = models.FileField()
    TIN = models.FileField()
    NBI_Clearance = models.FileField()
    Marriage_Contract = models.FileField()
    TOR = models.FileField()
    Picture = models.FileField()
    Employee_Certificate = models.FileField()
    Clearance_To_Transfer = models.FileField()
    Clearance_From_SSS = models.FileField()

    def __str__(self):
        requirements = "%s's Requirements" % (self.User.NickName)
        return self.requirements


class Education(models.Model):
    EducationID = models.AutoField(primary_key=True)
    User = models.OneToOneField(Applicant, on_delete=models.CASCADE)
    School_Name = models.CharField(max_length=70)
    Education_Attained = models.CharField(max_length=100)

    def __str__(self):
        educational = "%s %s's Educational Background" % (self.User.First_Name, self.User.Last_Name)
        return educational


class JobOpportunity(models.Model):
    JobID = models.AutoField(primary_key=True)
    Client_Name = models.ForeignKey(Client, on_delete=models.CASCADE)
    Job_Post = models.CharField(max_length=50)
    Required_Applicants = models.PositiveIntegerField()

    def __str__(self):
        job = "%s - Applicant required: %s" % (self.Job_Post, self.Required_Applicants)
        return job.strip()

    class Meta:
        verbose_name = _('Job Opportunity')
        verbose_name_plural = _('Job Opportunities')


class Specialized(models.Model):
    SpecSkillsID = models.AutoField(primary_key=True)
    User = models.OneToOneField(Applicant, on_delete=models.CASCADE)
    Specialization = models.CharField(max_length=50)
    SubSkill = models.CharField(max_length=50)

    def __str__(self):
        skill = "%s - %s" % (self.Specialization, self.SubSkill)
        return skill.strip()

    class Meta:
        verbose_name = _('Specialization')
        verbose_name_plural = _('Specializations')


class SkillMatching(models.Model):
    SMID = models.AutoField(primary_key=True)
    Job = models.ForeignKey(JobOpportunity, on_delete=models.CASCADE)
    SpecSkill = models.ManyToManyField(Specialized)

    def __str__(self):
        sm = "%s - %s" % (self.Job.Job_Post, "Skill Matched")
        return sm

jobportal/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic import CreateView
from .forms import EmployeeRegistration, ClientRegistration, ApplicantRegistration
from .forms import ApplicantLogin, EmployeeMatchSkill, EmployeeLogin, ClientLogin
from .models import Employee, Client, Applicant, Requirement, Education, JobOpportunity, Specialized, SkillMatching
from django.contrib.auth import authenticate, login as auth_login, logout
from django.core.urlresolvers import reverse_lazy

# Create your views here.


def index(request):
    return render(request, 'index.html')


def register(request):
    return render(request, 'register.html')


def login(request):
    return render(request, 'login.html')


def registerEmployee(request):
    if request.method == 'POST':
        employee_form = EmployeeRegistration(request.POST)
        if employee_form.is_valid():
            employee_form.save()
            return redirect('/accounts/employee/login')
        else:
            return render(request, 'employee/register.html', {'form': employee_form})

    else:
        employee_form = EmployeeRegistration()

        args = {'form': employee_form}
        return render(request, 'employee/register.html', args)


def registerClient(request):
    if request.method == 'POST':
        client_form = ClientRegistration(request.POST, request.FILES)
        if client_form.is_valid():
            client_form.save()
            return redirect('/accounts/client/login')
        else:
            return render(request, 'client/register.html', {'form': client_form})

    else:
        client_form = ClientRegistration()

        args = {'form': client_form}
        return render(request, 'client/register.html', args)


def registerApplicant(request):
    if request.method == 'POST':
        applicant_form = ApplicantRegistration(request.POST, request.FILES)
        if applicant_form.is_valid():
            applicant_form.save()
            return redirect('/accounts/applicant/login')
        else:
            return render(request, 'applicant/register.html', {'form': applicant_form})
    else:
        applicant_form = ApplicantRegistration()
        args = {'form': applicant_form}
        return render(request, 'applicant/register.html', args)


def loginApplicant(request):
    # print(request.user.is_authenticated())
    title = "Login"
    template_name = 'applicant/login.html'
    form = ApplicantLogin(request.POST or None)
    if form.is_valid():
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(username=email, password=password)
        auth_login(request, user)
        # print(request.user.is_authenticated())
        return redirect('/accounts/applicant/index')
    return render(request, template_name, {'form': form, 'title': title})


def loginEmployee(request):
    title = "Login"
    template_name = 'employee/login.html'
    form = EmployeeLogin(request.POST or None)
    if form.is_valid():
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(username=email, password=password)
        auth_login(request, user)
        # print(request.user.is_authenticated())
        return redirect('/accounts/employee/index')
    return render(request, template_name, {'form': form, 'title': title})


def loginClient(request):
    title = "Login"
    template_name = 'client/login.html'
    form = ClientLogin(request.POST or None)
    if form.is_valid():
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(username=email, password=password)
        auth_login(request, user)
        # print(request.user.is_authenticated())
        return redirect('/accounts/client/index')
    return render(request, template_name, {'form': form, 'title': title})


def logoutApplicant(request):
    logout(request)
    template_name = 'applicant/logout.html'
    return render(request, template_name)


def logoutEmployee(request):
    logout(request)
    template_name = 'employee/logout.html'
    return render(request, template_name)


def logoutClient(request):
    logout(request)
    template_name = 'client/logout.html'
    return render(request, template_name)


class indexApplicant(generic.TemplateView):
    template_name = 'applicant/index.html'
    model = Applicant
    context_object_name = 'applicant'

    def get_queryset(self):
        applicant = Applicant.objects.filter(user=self.request.user)
        return applicant


class indexClient(generic.TemplateView):
    template_name = 'client/index.html'
    model = Client
    context_object_name = 'client'

    def get_queryset(self):
        client = Client.objects.filter(user=self.request.user)
        return client


class indexEmployee(generic.TemplateView):
    template_name = 'employee/index.html'
    model = Employee
    context_object_name = 'employee'

    def get_queryset(self):
        employee = Employee.objects.filter(user=self.request.user)
        return employee


class requirementsApplicant(generic.CreateView):
    model = Requirement
    template_name = 'applicant/requirements.html'
    fields = ['SSS', 'Phil_Health', 'TIN', 'NBI_Clearance', 'Marriage_Contract', 'TOR',
              'Picture', 'Employee_Certificate', 'Clearance_To_Transfer', 'Clearance_From_SSS']

    success_url = reverse_lazy('accounts:applicant-index')

    def form_valid(self, form):
        form.instance.User = self.request.user.applicant
        return super(requirementsApplicant, self).form_valid(form)


class educationApplicant(generic.CreateView):
    model = Education
    template_name = 'applicant/educationform.html'
    fields = ['School_Name', 'Education_Attained']
    success_url = reverse_lazy('accounts:applicant-index')

    def form_valid(self, form):
        form.instance.User = self.request.user.applicant
        return super(educationApplicant, self).form_valid(form)


class jobopportunity(generic.CreateView):
    model = JobOpportunity
    template_name = 'client/job.html'
    fields = ['Job_Post', 'Required_Applicants']

    success_url = reverse_lazy('accounts:client-job')

    def form_valid(self, form):
        form.instance.User = self.request.user.client
        return super(jobopportunity, self).form_valid(form)


class skillApplicant(generic.CreateView):
    model = Specialized
    template_name = 'applicant/skills.html'
    fields = ['Specialization', 'SubSkill']

    success_url = reverse_lazy('accounts:applicant-skill')

    def form_valid(self, form):
        form.instance.User = self.request.user.applicant
        return super(skillApplicant, self).form_valid(form)


def matchSkill(request):
    if request.method == "POST":
        form = EmployeeMatchSkill(request.POST)
        if form.is_valid():
            match = form.save(commit=False)
            match.save()
            return redirect('accounts:employee-index')
    else:
        form = EmployeeMatchSkill()
    return render(request, 'employee/skillmatch.html', {'form': form})

jobportal/templates/client/index.html
{% extends 'base.html' %}
{% block title %}
Client Home Page
{% endblock %}
{% block dropdown %}
<li class="nav-item">
  <a href="{% url 'accounts:applicant-logout' %}" class="nav-link">Log Out</a>
</li>
{% endblock %}
{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Hello, {{ user.First_Name }} {{ user.Last_Name }}
      <!-- {% if user.applicant.Gender == "Male" %}
      Mr.
      {% endif %}
      {% if user.applicant.Gender == "Female" and user.applicant.Civil_Status == "Single" %}
      Ms. {{ user.First_Name }} {{ user.Last_Name }}
      {% endif %}
      {% if user.applicant.Gender == "Female" and user.applicant.Civil_Status == "Married" %}
      Mrs. {{ user.First_Name }} {{ user.Last_Name }}
      {% endif %} -->
    </h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="m-y-md">
    <p>To futher advance your applicantion, you are required to submit requirements and fill up the education form.</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{% url 'accounts:client-job' %}" role="button">Jobs</a>
      <!-- <a class="btn btn-primary btn-lg" href="{% url 'accounts:applicant-education' %}" role="button">Education</a> -->
    </p>
  </div>
</div>
<div class="container">
  <div class="col-sm-12 col-md-12">
    <h3>Client's Data</h3>
    <hr>
    <div class="row">
      <div class="col-sm-5 col-md-3">
        <img class="rounded img-fluid" src="{{ user.client.Logo.url }}" style="width: 250px;" alt="No Picture">
      </div>
      <div class="col-sm-7 col-md-9">
        <p><h4>Company Name: {{ user.client.Company_Name }}</h4></p>
        <div class="row">
          <div class="col-sm-3 col-md-4">
            <p>Name: <strong>{{ user.Last_Name }}, {{ user.First_Name }}</strong></p>
            <!-- <p>Gender: {{ user.client.Gender }}</p>
            <p>Civil Status: {{ user.client.Civil_Status }}</p> -->
            <p>Phone: {{ user.client.Phone }}</p>
          </div>
          <div class="col-sm-4 col-md-5">
            <p>Address: {{ user.client.Bldg_No }}, {{ user.client.Street }},
                        {{ user.client.Municipality }}, {{ user.client.City }},
                        {{ user.client.Country }}
            </p>
            <!-- <p>Birth Date: {{ user.applicant.Birth_Date }}</p>
            <p>Birth Place: {{ user.applicant.Birth_Place }}</p> -->
            <p>Mobile: {{ user.client.Mobile }}</p>
            <p>Website: <a href="{{ user.client.Website}}">{{ user.client.Website}}</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- <p>{{ applicant.NickName }}</p> -->
</div>
{% endblock %}

jobportal/templates/client/job.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Job Request
{% endblock %}
{% block hrefbrand %}
{% url 'accounts:client-index' %}
{% endblock %}
{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Jobs</h1>
    <!-- <p class="lead">Set your skills to be compared with job request</p> -->
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-sm-6 col-md-12">
          <form class="form=horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-outline-success btn-block">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

jobportal/templates/client/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Client Login{% endblock %}
{% block hrefbrand %}
{% url 'index' %}
{% endblock %}
{% block dropdown %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'register' %}">Register</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'login' %}">Log In</a>
</li>
{% endblock %}
{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Log In</h1>
    <p class="lead">Enter your email and password to login</p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-sm-3 col-md-6">
          <form class="form=horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-outline-primary">Submit</button>
            </div>
          </form>
        </div>
        <div class="col-sm-3 col-md-6">
          <h3>Got no Account?</h3>
          <hr>
          <p class="text-center"><a href="{% url 'accounts:employee-add' %}">Register as Employee</a></p>
          <p class="text-center"><a href="{% url 'accounts:client-add' %}">Register as Client</a></p>
          <p class="text-center"><a href="{% url 'accounts:applicant-add' %}">Register as Applicant</a></p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

jobportal/templates/client/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block meta %}<meta http-equiv="refresh" content="1.5;url={% url 'index' %}">{% endblock %}
{% block title %}Applicant Login{% endblock %}
{% block dropdown %}
<li class="nav-item">
  <a class="nav-link" href="#">Register</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="#">Log In</a>
</li>
{% endblock %}
{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1 display-4>Log out</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-sm-6 col-md-12">
          <p>Client is logged out</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

jobportal/templates/client/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block hrefbrand %}
{% url 'index' %}
{% endblock %}
{% block dropdown %}
<li class="nav-item">
  <a class="nav-link" href="{% url 'register' %}">Register</a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{% url 'login' %}">Log In</a>
</li>
{% endblock %}
{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Welcome to the Registration Form</h1>
    <p class="lead">Register your company for an easier transaction with ours and move</p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-sm-6 col-md-12">
          <form class="form=horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-outline-success btn-block">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- <div class="col-md-6 text-center">
      <img class="img-fluid " src="{% static 'webimages/vertical1.png' %}" alt="">
    </div> -->
  </div>
</div>
{% endblock %}